---

version: 2
jobs:
  lint:
    docker:
      - image: canonicalwebteam/dev
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip3 install flake8 black
      - run:
          name: Check syntax with Flake8
          command: flake8
      - run:
          name: Check Black has been run
          command: black --line-length 79 --check canonicalwebteam
  test:
    docker:
      - image: canonicalwebteam/dev
    steps:
      - checkout
      - run:
          name: Install the module
          command: pip3 install .
      - run:
          name: Install dependencies for running tests
          command: pip3 install pytest flask_testing requests
      - run:
          name: Run tests with pytest
          command: pytest tests
workflows:
  version: 2
  build:
    jobs:
      - lint
      - test
